---
- hosts: chroots
  gather_facts: no
  remote_user: root
  connection: chroot

  vars:
    default_language: en_US
    default_encoding: UTF-8
    default_hostname: arch
    time_zone: Europe
    time_subzone: London

  tasks:
  - name: Configure the hostname
    command: echo "{{default_hostname}}" > /etc/hostname
  - name: Configure the timezone
    file:
      src: "/usr/share/zoneinfo/{{time_zone}}/{{time_subzone}}"
      dest: /etc/localtime
      state: link
  - name: Configure the locale
    lineinfile:
      path: /etc/locale.gen
      regexp: "#{{default_language}}.{{default_encoding}} {{default_encoding}}"
      line: "{{default_language}}.{{default_encoding}} {{default_encoding}}"
  - name: Generate the locale settings
    command: locale-gen
  - name: Save the locale
    copy: content="LANG={{default_language}}.{{default_encoding}}" dest=/etc/locale.conf
  - name: Configure the swappiness
    copy:
      content: "vm.swappiness=10"
      dest: /etc/sysctl.d/99-swapiness.conf

  - name: Enable GDM
    systemd: enabled=yes name=gdm.service
  - name: Enable Network Manager
    systemd: enabled=yes name=NetworkManager.service

  - name: Create the main user
    user:
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512') }}"
      shell: /bin/bash
      group: users
      groups: wheel,storage,power
  - name: Enable sudo for wheel
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: "# %wheel ALL=(ALL) ALL"
      line: "%wheel ALL=(ALL) ALL"
