---
- hosts: localhost
  gather_facts: no
  connection: local

  vars:
    terminal_profile: default
    terminal_profile_uuid: "{{ terminal_profile | to_uuid }}"

  tasks:
    - name: Get current terminal profiles
      dconf:
        state: read
        key: "/org/gnome/terminal/legacy/profiles:/list"
      register: current_profiles
    - set_fact: new_profiles="['{{ terminal_profile_uuid }}'] {% if current_profiles.value %} + {{ current_profiles.value }} {% endif %}"
    - name: Setup styles
      dconf:
        state: present
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "/org/gnome/desktop/interface/gtk-theme", value: "'Adwaita-dark'" }
        - { key: "/org/gnome/terminal/legacy/new-terminal-mode", value: "'tab'" }
        - { key: "/org/gnome/terminal/legacy/profiles:/list", value: "{{ new_profiles | unique }}" }
        - { key: "/org/gnome/terminal/legacy/profiles:/default", value: "'{{ terminal_profile_uuid }}'" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:{{terminal_profile_uuid}}/audible-bell", value: "false" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:{{terminal_profile_uuid}}/use-system-font", value: "false" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:{{terminal_profile_uuid}}/font", value: "'Input Mono Condensed, Condensed 12'" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:{{terminal_profile_uuid}}/visible-name", value: "'{{ terminal_profile }}'" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:{{terminal_profile_uuid}}/default-size-columns", value: "105" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:{{terminal_profile_uuid}}/default-size-rows", value: "48" }
        - { key: "/org/gnome/settings-daemon/plugins/xsettings/antialiasing", value: "'rgba'" }
        - { key: "/org/gnome/settings-daemon/plugins/xsettings/hinting", value: "'slight'" }
